
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import movie.movieDAO;
import movie.movieDTO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author juhoonlee
 */
public class ChooseSeatFrame extends javax.swing.JFrame {

    /**
     * Creates new form chooseSeat
     */
    String id;
    String movie;
    public ChooseSeatFrame(movieDTO dto, String id) {
        initComponents();
        setLocationRelativeTo(null);
        this.id = id;
        movie = dto.Getmovie();
        movieDAO dao = new movieDAO();
        int available[] = dao.seat(dto.Getmovie());
        if(available[0] == 1){
            seatA1.setEnabled(false);
        }
        if(available[1] == 1){
            seatA2.setEnabled(false);
        }
        if(available[2] == 1){
            seatA3.setEnabled(false);
        }
        if(available[3] == 1){
            seatA4.setEnabled(false);
        }
        if(available[4] == 1){
            seatA5.setEnabled(false);
        }
        if(available[5] == 1){
            seatA6.setEnabled(false);
        }
        if(available[6] == 1){
            seatA7.setEnabled(false);
        }
        if(available[7] == 1){
            seatA8.setEnabled(false);
        }
        if(available[8] == 1){
            seatB1.setEnabled(false);
        }
        if(available[9] == 1){
            seatB2.setEnabled(false);
        }
        if(available[10] == 1){
            seatB3.setEnabled(false);
        }
        if(available[11] == 1){
            seatB4.setEnabled(false);
        }
        if(available[12] == 1){
            seatB5.setEnabled(false);
        }
        if(available[13] == 1){
            seatB6.setEnabled(false);
        }
        if(available[14] == 1){
            seatB7.setEnabled(false);
        }
        if(available[15] == 1){
            seatB8.setEnabled(false);
        }
        if(available[16] == 1){
            seatC1.setEnabled(false);
        }
        if(available[17] == 1){
            seatC2.setEnabled(false);
        }
        if(available[18] == 1){
            seatC3.setEnabled(false);
        }
        if(available[19] == 1){
            seatC4.setEnabled(false);
        }
        if(available[20] == 1){
            seatC5.setEnabled(false);
        }
        if(available[21] == 1){
            seatC6.setEnabled(false);
        }
        if(available[22] == 1){
            seatC7.setEnabled(false);
        }
        if(available[23] == 1){
            seatC8.setEnabled(false);
        }
        if(available[24] == 1){
            seatD1.setEnabled(false);
        }
        if(available[25] == 1){
            seatD2.setEnabled(false);
        }
        if(available[26] == 1){
            seatD3.setEnabled(false);
        }
        if(available[27] == 1){
            seatD4.setEnabled(false);
        }
        if(available[28] == 1){
            seatD5.setEnabled(false);
        }
        if(available[29] == 1){
            seatD6.setEnabled(false);
        }
        if(available[30] == 1){
            seatD7.setEnabled(false);
        }
        if(available[31] == 1){
            seatD8.setEnabled(false);
        }
        
    }
    
    ArrayList<String> list = new ArrayList<>();
    
    public void reservationResult(){
        int price = Integer.parseInt(resultPrice.getText()) + 15000;
        int count = Integer.parseInt(resultCount.getText()) + 1;
        resultPrice.setText(Integer.toString(price));
        resultCount.setText(Integer.toString(count));
    }
    
    public void deleteReservation(){
        int price = Integer.parseInt(resultPrice.getText()) - 15000;
        int count = Integer.parseInt(resultCount.getText()) - 1;
        resultPrice.setText(Integer.toString(price));
        resultCount.setText(Integer.toString(count));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seatScreen = new javax.swing.JLabel();
        seatA1 = new javax.swing.JCheckBox();
        seatA2 = new javax.swing.JCheckBox();
        seatB1 = new javax.swing.JCheckBox();
        seatB2 = new javax.swing.JCheckBox();
        seatC1 = new javax.swing.JCheckBox();
        seatC2 = new javax.swing.JCheckBox();
        seatD1 = new javax.swing.JCheckBox();
        seatD2 = new javax.swing.JCheckBox();
        seatC4 = new javax.swing.JCheckBox();
        seatD3 = new javax.swing.JCheckBox();
        seatD4 = new javax.swing.JCheckBox();
        seatA3 = new javax.swing.JCheckBox();
        seatA4 = new javax.swing.JCheckBox();
        seatB3 = new javax.swing.JCheckBox();
        seatB4 = new javax.swing.JCheckBox();
        seatC3 = new javax.swing.JCheckBox();
        seatC6 = new javax.swing.JCheckBox();
        seatD5 = new javax.swing.JCheckBox();
        seatD6 = new javax.swing.JCheckBox();
        seatA5 = new javax.swing.JCheckBox();
        seatA6 = new javax.swing.JCheckBox();
        seatB5 = new javax.swing.JCheckBox();
        seatB6 = new javax.swing.JCheckBox();
        seatC5 = new javax.swing.JCheckBox();
        seatC8 = new javax.swing.JCheckBox();
        seatD7 = new javax.swing.JCheckBox();
        seatD8 = new javax.swing.JCheckBox();
        seatA7 = new javax.swing.JCheckBox();
        seatA8 = new javax.swing.JCheckBox();
        seatB7 = new javax.swing.JCheckBox();
        seatB8 = new javax.swing.JCheckBox();
        seatC7 = new javax.swing.JCheckBox();
        seatPrice = new javax.swing.JLabel();
        seatCount = new javax.swing.JLabel();
        seatPay = new javax.swing.JButton();
        resultPrice = new javax.swing.JLabel();
        resultCount = new javax.swing.JLabel();
        backFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seatScreen.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        seatScreen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seatScreen.setText("screen");

        seatA1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA1.setText("A1");
        seatA1.setSize(new java.awt.Dimension(30, 30));
        seatA1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA1ItemStateChanged(evt);
            }
        });

        seatA2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA2.setText("A2");
        seatA2.setSize(new java.awt.Dimension(30, 30));
        seatA2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA2ItemStateChanged(evt);
            }
        });

        seatB1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB1.setText("B1");
        seatB1.setSize(new java.awt.Dimension(30, 30));
        seatB1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB1ItemStateChanged(evt);
            }
        });

        seatB2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB2.setText("B2");
        seatB2.setSize(new java.awt.Dimension(30, 30));
        seatB2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB2ItemStateChanged(evt);
            }
        });

        seatC1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC1.setText("C1");
        seatC1.setSize(new java.awt.Dimension(30, 30));
        seatC1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC1ItemStateChanged(evt);
            }
        });

        seatC2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC2.setText("C2");
        seatC2.setSize(new java.awt.Dimension(30, 30));
        seatC2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC2ItemStateChanged(evt);
            }
        });

        seatD1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD1.setText("D1");
        seatD1.setSize(new java.awt.Dimension(30, 30));
        seatD1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD1ItemStateChanged(evt);
            }
        });

        seatD2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD2.setText("D2");
        seatD2.setSize(new java.awt.Dimension(30, 30));
        seatD2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD2ItemStateChanged(evt);
            }
        });

        seatC4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC4.setText("C4");
        seatC4.setSize(new java.awt.Dimension(30, 30));
        seatC4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC4ItemStateChanged(evt);
            }
        });

        seatD3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD3.setText("D3");
        seatD3.setSize(new java.awt.Dimension(30, 30));
        seatD3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD3ItemStateChanged(evt);
            }
        });

        seatD4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD4.setText("D4");
        seatD4.setSize(new java.awt.Dimension(30, 30));
        seatD4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD4ItemStateChanged(evt);
            }
        });

        seatA3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA3.setText("A3");
        seatA3.setSize(new java.awt.Dimension(30, 30));
        seatA3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA3ItemStateChanged(evt);
            }
        });

        seatA4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA4.setText("A4");
        seatA4.setSize(new java.awt.Dimension(30, 30));
        seatA4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA4ItemStateChanged(evt);
            }
        });

        seatB3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB3.setText("B3");
        seatB3.setSize(new java.awt.Dimension(30, 30));
        seatB3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB3ItemStateChanged(evt);
            }
        });

        seatB4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB4.setText("B4");
        seatB4.setSize(new java.awt.Dimension(30, 30));
        seatB4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB4ItemStateChanged(evt);
            }
        });

        seatC3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC3.setText("C3");
        seatC3.setSize(new java.awt.Dimension(30, 30));
        seatC3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC3ItemStateChanged(evt);
            }
        });

        seatC6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC6.setText("C6");
        seatC6.setSize(new java.awt.Dimension(30, 30));
        seatC6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC6ItemStateChanged(evt);
            }
        });

        seatD5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD5.setText("D5");
        seatD5.setSize(new java.awt.Dimension(30, 30));
        seatD5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD5ItemStateChanged(evt);
            }
        });

        seatD6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD6.setText("D6");
        seatD6.setSize(new java.awt.Dimension(30, 30));
        seatD6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD6ItemStateChanged(evt);
            }
        });

        seatA5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA5.setText("A5");
        seatA5.setSize(new java.awt.Dimension(30, 30));
        seatA5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA5ItemStateChanged(evt);
            }
        });

        seatA6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA6.setText("A6");
        seatA6.setSize(new java.awt.Dimension(30, 30));
        seatA6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA6ItemStateChanged(evt);
            }
        });

        seatB5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB5.setText("B5");
        seatB5.setSize(new java.awt.Dimension(30, 30));
        seatB5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB5ItemStateChanged(evt);
            }
        });

        seatB6.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB6.setText("B6");
        seatB6.setSize(new java.awt.Dimension(30, 30));
        seatB6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB6ItemStateChanged(evt);
            }
        });

        seatC5.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC5.setText("C5");
        seatC5.setSize(new java.awt.Dimension(30, 30));
        seatC5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC5ItemStateChanged(evt);
            }
        });

        seatC8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC8.setText("C8");
        seatC8.setSize(new java.awt.Dimension(30, 30));
        seatC8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC8ItemStateChanged(evt);
            }
        });

        seatD7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD7.setText("D7");
        seatD7.setSize(new java.awt.Dimension(30, 30));
        seatD7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD7ItemStateChanged(evt);
            }
        });

        seatD8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatD8.setText("D8");
        seatD8.setSize(new java.awt.Dimension(30, 30));
        seatD8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatD8ItemStateChanged(evt);
            }
        });

        seatA7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA7.setText("A7");
        seatA7.setSize(new java.awt.Dimension(30, 30));
        seatA7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA7ItemStateChanged(evt);
            }
        });

        seatA8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatA8.setText("A8");
        seatA8.setSize(new java.awt.Dimension(30, 30));
        seatA8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatA8ItemStateChanged(evt);
            }
        });

        seatB7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB7.setText("B7");
        seatB7.setSize(new java.awt.Dimension(30, 30));
        seatB7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB7ItemStateChanged(evt);
            }
        });

        seatB8.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatB8.setText("B8");
        seatB8.setSize(new java.awt.Dimension(30, 30));
        seatB8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatB8ItemStateChanged(evt);
            }
        });

        seatC7.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatC7.setText("C7");
        seatC7.setSize(new java.awt.Dimension(30, 30));
        seatC7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                seatC7ItemStateChanged(evt);
            }
        });

        seatPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatPrice.setText("금   액:");

        seatCount.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatCount.setText("인원수:");

        seatPay.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        seatPay.setText("결제하기");
        seatPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatPayActionPerformed(evt);
            }
        });

        resultPrice.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        resultPrice.setText("0");

        resultCount.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        resultCount.setText("0");

        backFrame.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        backFrame.setText("뒤로가기");
        backFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seatScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatA2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatD1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatA3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatA4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatB4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatC4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatD3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatA5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatA6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatB5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatB6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatC5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatC6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seatD5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(seatD6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(seatCount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(seatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(resultPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(resultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seatA7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(seatA8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(backFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(seatPay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(seatB7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(seatB8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(seatC7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(seatC8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(seatD7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(seatD8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(seatScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(seatA2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatA1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatB1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatB2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatC1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatC2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatD1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatD2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatA3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatA4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatB3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatB4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatC3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatC4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatD3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatD4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatA5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatA6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatB5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatB6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatC5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatC6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(seatD5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(seatD6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatA7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatA8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatB7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatB8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatC7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatC8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seatD7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatD8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seatPay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resultPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seatPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seatCount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seatPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatPayActionPerformed
        int result = 0;
        String str = "";
        movieDAO dao = new movieDAO();
        for(int i=0; i<list.size(); i++){
            result = dao.reservation(list.get(i), movie);
            str += list.get(i) + ", ";
        }
        if(result > 0){
            JOptionPane.showMessageDialog(null, "예약 성공");
            dispose();
            new MovieReceiptFrame(id, resultPrice.getText(), str, movie);
        }else{
            JOptionPane.showMessageDialog(null, "예약 실패");
        }
    }//GEN-LAST:event_seatPayActionPerformed

    private void backFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFrameActionPerformed
        dispose();
        new MovieFrame(id);
    }//GEN-LAST:event_backFrameActionPerformed

    private void seatC5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC5ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC5.getText());
            reservationResult();
        }else{
            list.remove(seatC5.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC5ItemStateChanged

    private void seatA1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA1.getText());
            reservationResult();
        }else{
            list.remove(seatA1.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA1ItemStateChanged

    private void seatA2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA2ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA2.getText());
            reservationResult();
        }else{
            list.remove(seatA2.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA2ItemStateChanged

    private void seatA3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA3ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA3.getText());
            reservationResult();
        }else{
            list.remove(seatA3.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA3ItemStateChanged

    private void seatA6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA6ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA6.getText());
            reservationResult();
        }else{
            list.remove(seatA6.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA6ItemStateChanged

    private void seatA7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA7ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA7.getText());
            reservationResult();
        }else{
            list.remove(seatA7.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA7ItemStateChanged

    private void seatB1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB1.getText());
            reservationResult();
        }else{
            list.remove(seatB1.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB1ItemStateChanged

    private void seatB2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB2ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB2.getText());
            reservationResult();
        }else{
            list.remove(seatB2.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB2ItemStateChanged

    private void seatB4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB4ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB4.getText());
            reservationResult();
        }else{
            list.remove(seatB4.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB4ItemStateChanged

    private void seatB5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB5ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB5.getText());
            reservationResult();
        }else{
            list.remove(seatB5.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB5ItemStateChanged

    private void seatB6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB6ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB6.getText());
            reservationResult();
        }else{
            list.remove(seatB6.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB6ItemStateChanged

    private void seatB7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB7ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB7.getText());
            reservationResult();
        }else{
            list.remove(seatB7.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB7ItemStateChanged

    private void seatB8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB8ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB8.getText());
            reservationResult();
        }else{
            list.remove(seatB8.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB8ItemStateChanged

    private void seatC1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC1.getText());
            reservationResult();
        }else{
            list.remove(seatC1.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC1ItemStateChanged

    private void seatC2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC2ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC2.getText());
            reservationResult();
        }else{
            list.remove(seatC2.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC2ItemStateChanged

    private void seatC3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC3ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC3.getText());
            reservationResult();
        }else{
            list.remove(seatC3.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC3ItemStateChanged

    private void seatC4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC4ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC4.getText());
            reservationResult();
        }else{
            list.remove(seatC4.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC4ItemStateChanged

    private void seatC6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC6ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC6.getText());
            reservationResult();
        }else{
            list.remove(seatC6.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC6ItemStateChanged

    private void seatC7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC7ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC7.getText());
            reservationResult();
        }else{
            list.remove(seatC7.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC7ItemStateChanged

    private void seatC8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatC8ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatC8.getText());
            reservationResult();
        }else{
            list.remove(seatC8.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatC8ItemStateChanged

    private void seatD1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD1ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD1.getText());
            reservationResult();
        }else{
            list.remove(seatD1.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD1ItemStateChanged

    private void seatD2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD2ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD2.getText());
            reservationResult();
        }else{
            list.remove(seatD2.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD2ItemStateChanged

    private void seatD3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD3ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD3.getText());
            reservationResult();
        }else{
            list.remove(seatD3.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD3ItemStateChanged

    private void seatD4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD4ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD4.getText());
            reservationResult();
        }else{
            list.remove(seatD4.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD4ItemStateChanged

    private void seatD5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD5ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD5.getText());
            reservationResult();
        }else{
            list.remove(seatD5.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD5ItemStateChanged

    private void seatD6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD6ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD6.getText());
            reservationResult();
        }else{
            list.remove(seatD6.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD6ItemStateChanged

    private void seatD7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD7ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD7.getText());
            reservationResult();
        }else{
            list.remove(seatD7.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD7ItemStateChanged

    private void seatA4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA4ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA4.getText());
            reservationResult();
        }else{
            list.remove(seatA4.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA4ItemStateChanged

    private void seatA5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA5ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA5.getText());
            reservationResult();
        }else{
            list.remove(seatA5.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA5ItemStateChanged

    private void seatA8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatA8ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatA8.getText());
            reservationResult();
        }else{
            list.remove(seatA8.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatA8ItemStateChanged

    private void seatD8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatD8ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatD8.getText());
            reservationResult();
        }else{
            list.remove(seatD8.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatD8ItemStateChanged

    private void seatB3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_seatB3ItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED){
            list.add(seatB3.getText());
            reservationResult();
        }else{
            list.remove(seatB3.getText());
            deleteReservation();
        }
    }//GEN-LAST:event_seatB3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseSeatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backFrame;
    private javax.swing.JLabel resultCount;
    private javax.swing.JLabel resultPrice;
    private javax.swing.JCheckBox seatA1;
    private javax.swing.JCheckBox seatA2;
    private javax.swing.JCheckBox seatA3;
    private javax.swing.JCheckBox seatA4;
    private javax.swing.JCheckBox seatA5;
    private javax.swing.JCheckBox seatA6;
    private javax.swing.JCheckBox seatA7;
    private javax.swing.JCheckBox seatA8;
    private javax.swing.JCheckBox seatB1;
    private javax.swing.JCheckBox seatB2;
    private javax.swing.JCheckBox seatB3;
    private javax.swing.JCheckBox seatB4;
    private javax.swing.JCheckBox seatB5;
    private javax.swing.JCheckBox seatB6;
    private javax.swing.JCheckBox seatB7;
    private javax.swing.JCheckBox seatB8;
    private javax.swing.JCheckBox seatC1;
    private javax.swing.JCheckBox seatC2;
    private javax.swing.JCheckBox seatC3;
    private javax.swing.JCheckBox seatC4;
    private javax.swing.JCheckBox seatC5;
    private javax.swing.JCheckBox seatC6;
    private javax.swing.JCheckBox seatC7;
    private javax.swing.JCheckBox seatC8;
    private javax.swing.JLabel seatCount;
    private javax.swing.JCheckBox seatD1;
    private javax.swing.JCheckBox seatD2;
    private javax.swing.JCheckBox seatD3;
    private javax.swing.JCheckBox seatD4;
    private javax.swing.JCheckBox seatD5;
    private javax.swing.JCheckBox seatD6;
    private javax.swing.JCheckBox seatD7;
    private javax.swing.JCheckBox seatD8;
    private javax.swing.JButton seatPay;
    private javax.swing.JLabel seatPrice;
    private javax.swing.JLabel seatScreen;
    // End of variables declaration//GEN-END:variables
}
