
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import user.userDAO;
import user.userDTO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author 표유림
 */
public class JoinFrame extends javax.swing.JFrame {

    /**
     * Creates new form JoinFrame
     */
    public JoinFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        id = new javax.swing.JLabel();
        pw = new javax.swing.JLabel();
        joinId = new javax.swing.JTextField();
        joinPassword = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        joinName = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        joinEmail = new javax.swing.JTextField();
        gender = new javax.swing.JLabel();
        joinMan = new javax.swing.JRadioButton();
        joinWomen = new javax.swing.JRadioButton();
        joinAction = new javax.swing.JButton();
        backFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        id.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        id.setText("아이디 :");

        pw.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        pw.setText("비밀번호 :");

        joinId.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        joinPassword.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        name.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        name.setText("닉네임 :");

        joinName.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        email.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        email.setText("이메일 :");

        joinEmail.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        gender.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        gender.setText("성별 :");

        buttonGroup1.add(joinMan);
        joinMan.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        joinMan.setSelected(true);
        joinMan.setText("남");

        buttonGroup1.add(joinWomen);
        joinWomen.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        joinWomen.setText("여");

        joinAction.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        joinAction.setText("회원가입");
        joinAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinActionActionPerformed(evt);
            }
        });

        backFrame.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        backFrame.setText("뒤로가기");
        backFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(joinId, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(joinPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(joinName)
                                .addComponent(joinEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(joinMan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(joinWomen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(backFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(joinAction, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pw, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(joinId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(joinPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinName, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinMan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinWomen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(joinAction, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFrameActionPerformed
        new LoginFrame();
        dispose();
    }//GEN-LAST:event_backFrameActionPerformed

    private void joinActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinActionActionPerformed
        userDTO dto = new userDTO();
        userDAO dao = new userDAO();
        dto.setId(joinId.getText());
        dto.setPw(joinPassword.getText());
        dto.setName(joinName.getText());
        if(joinMan.isSelected()){
            dto.setEmail(joinMan.getText());
        }
        if(joinWomen.isSelected()){
            dto.setEmail(joinWomen.getText());
        }
        
        if(joinId.getText().equals("") || joinPassword.getText().equals("") || joinName.getText().equals("") || joinEmail.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "빈 칸이 있습니다 다시 입력해주세요.");
        }else{
        try {
            int duplicate = dao.joinCheck(dto.getId());
            if(duplicate == 1){
                JOptionPane.showMessageDialog(null, "이미 존재하는 아이디입니다.");
                dispose();
                new JoinFrame();
            }else{
                int resultUser = dao.joinUser(dto);
                int resultInfo = dao.joinUserInfo(dto);
                if(resultUser > 0 && resultInfo > 0){
                    JOptionPane.showMessageDialog(null, "회원 가입에 성공하셨습니다.");
                    dispose();
                    new MainFrame2(dto.getId());
                }else{
                    JOptionPane.showMessageDialog(null, "회원 가입에 실패하셨습니다.");
                }
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JoinFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
        
        
    }//GEN-LAST:event_joinActionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backFrame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel id;
    private javax.swing.JButton joinAction;
    private javax.swing.JTextField joinEmail;
    private javax.swing.JTextField joinId;
    private javax.swing.JRadioButton joinMan;
    private javax.swing.JTextField joinName;
    private javax.swing.JTextField joinPassword;
    private javax.swing.JRadioButton joinWomen;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pw;
    // End of variables declaration//GEN-END:variables
}
