import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import movie.movieDTO;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author juhoonlee
 */
public class MovieFrame extends javax.swing.JFrame {

    /**
     * Creates new form movie
     */
    String id;
    public MovieFrame(String id) {
        initComponents();
        this.id = id;
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        gongTitle = new javax.swing.JCheckBox();
        beomTitle = new javax.swing.JCheckBox();
        maTitle = new javax.swing.JCheckBox();
        gongGenre = new javax.swing.JLabel();
        gongSeat = new javax.swing.JLabel();
        gongGrade = new javax.swing.JLabel();
        beomSeat = new javax.swing.JLabel();
        beomGrade = new javax.swing.JLabel();
        beomGenre = new javax.swing.JLabel();
        maSeat = new javax.swing.JLabel();
        maGrade = new javax.swing.JLabel();
        maGenre = new javax.swing.JLabel();
        chooseSeatNum = new javax.swing.JButton();
        movieSelect = new javax.swing.JLabel();
        backFrame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(gongTitle);
        gongTitle.setText("공조2");

        buttonGroup1.add(beomTitle);
        beomTitle.setText("범죄도시2");

        buttonGroup1.add(maTitle);
        maTitle.setText("마녀2");

        gongGenre.setText("장르: 액션");

        gongSeat.setText("좌석수: 32석");

        gongGrade.setText("평점: 8.01");

        beomSeat.setText("좌석수: 32석");

        beomGrade.setText("평점: 9.01");

        beomGenre.setText("장르: 범죄");

        maSeat.setText("좌석수: 32석");

        maGrade.setText("평점: 6.99");

        maGenre.setText("장르: 액션");

        chooseSeatNum.setText("좌석선택");
        chooseSeatNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseSeatNumActionPerformed(evt);
            }
        });

        movieSelect.setText("영화선택");

        backFrame.setText("뒤로가기");
        backFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backFrameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(173, 173, 173)
                .addComponent(movieSelect)
                .addContainerGap(183, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(beomTitle)
                                    .addComponent(gongTitle))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(gongGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gongSeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(gongGenre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(beomSeat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(beomGenre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(beomGrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maTitle)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maSeat)
                                    .addComponent(maGenre)
                                    .addComponent(maGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backFrame)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chooseSeatNum)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(movieSelect)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gongTitle)
                    .addComponent(gongGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gongSeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gongGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beomTitle)
                    .addComponent(beomGenre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beomSeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(beomGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maGenre)
                    .addComponent(maTitle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maSeat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(maGrade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseSeatNum)
                    .addComponent(backFrame))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void chooseSeatNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseSeatNumActionPerformed
        movieDTO movie = new movieDTO();
        if(gongTitle.isSelected()){
            movie.Setmovie("movie1");
        }
        if(beomTitle.isSelected()){
            movie.Setmovie("movie2");
        }
        if(maTitle.isSelected()){
            movie.Setmovie("movie3");
        }
        
        if(movie.Getmovie() == null){
            JOptionPane.showMessageDialog(null, "영화가 선택되지 않았습니다.");
        }
        
        ChooseSeatFrame seat = new ChooseSeatFrame(movie, id);
        seat.setLocationRelativeTo(null);
        seat.setVisible(true);
        dispose();
    }//GEN-LAST:event_chooseSeatNumActionPerformed

    private void backFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backFrameActionPerformed
        dispose();
        new MainFrame2(id);
    }//GEN-LAST:event_backFrameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backFrame;
    private javax.swing.JLabel beomGenre;
    private javax.swing.JLabel beomGrade;
    private javax.swing.JLabel beomSeat;
    private javax.swing.JCheckBox beomTitle;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton chooseSeatNum;
    private javax.swing.JLabel gongGenre;
    private javax.swing.JLabel gongGrade;
    private javax.swing.JLabel gongSeat;
    private javax.swing.JCheckBox gongTitle;
    private javax.swing.JLabel maGenre;
    private javax.swing.JLabel maGrade;
    private javax.swing.JLabel maSeat;
    private javax.swing.JCheckBox maTitle;
    private javax.swing.JLabel movieSelect;
    // End of variables declaration//GEN-END:variables
}
