/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hansohee
 */
public class storeFrame extends javax.swing.JFrame {

    /**
     * Creates new form storeFrame
     */
    public storeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        ChkCoke = new javax.swing.JCheckBox();
        ChkCider = new javax.swing.JCheckBox();
        ChkFanta = new javax.swing.JCheckBox();
        ChkWater = new javax.swing.JCheckBox();
        ChkIceTea = new javax.swing.JCheckBox();
        ChkIceAmericano = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        ChkSweet = new javax.swing.JCheckBox();
        btnNutty = new javax.swing.JCheckBox();
        btnOnion = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        ChkSquid = new javax.swing.JCheckBox();
        ChkHotdog = new javax.swing.JCheckBox();
        ChkNacho = new javax.swing.JCheckBox();
        ChkCheeseball = new javax.swing.JCheckBox();
        btnPay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSelected = new javax.swing.JTextArea();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("주유소 영화관 매점");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N

        ChkCoke.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkCoke.setText("콜라 (2,500원)");

        ChkCider.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkCider.setText("사이다(2,500원)");

        ChkFanta.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkFanta.setText("환타 (2,500원)");

        ChkWater.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkWater.setText("생수 (2,000원)");

        ChkIceTea.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkIceTea.setText("아이스티 (3,000원)");

        ChkIceAmericano.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkIceAmericano.setText("아이스아메리카노 (4,000원)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkCoke)
                    .addComponent(ChkWater))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkCider)
                    .addComponent(ChkIceTea))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChkIceAmericano)
                    .addComponent(ChkFanta))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkCoke)
                    .addComponent(ChkCider)
                    .addComponent(ChkFanta))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkWater)
                    .addComponent(ChkIceTea)
                    .addComponent(ChkIceAmericano))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("음료", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ChkSweet.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkSweet.setText("달콤 팝콘 (5,000원)");

        btnNutty.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnNutty.setText("고소 팝콘 (5,500원)");

        btnOnion.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnOnion.setText("어니언팝콘 (5,500원)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChkSweet)
                .addGap(31, 31, 31)
                .addComponent(btnNutty)
                .addGap(18, 18, 18)
                .addComponent(btnOnion)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkSweet)
                    .addComponent(btnNutty)
                    .addComponent(btnOnion))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("팝콘", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ChkSquid.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkSquid.setText("즉석구이오징어 (5,000원)");

        ChkHotdog.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkHotdog.setText("핫도그 (4,500원)");

        ChkNacho.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkNacho.setText("칠리치즈나쵸 (4,900원)");

        ChkCheeseball.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        ChkCheeseball.setText("치즈볼 (4,500원)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ChkSquid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ChkHotdog))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ChkNacho)
                        .addGap(78, 78, 78)
                        .addComponent(ChkCheeseball)))
                .addContainerGap(124, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkSquid)
                    .addComponent(ChkHotdog))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChkNacho)
                    .addComponent(ChkCheeseball))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("스낵", jPanel3);

        btnPay.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnPay.setText("결제하기");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("선택한 제품");

        txtSelected.setColumns(20);
        txtSelected.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        txtSelected.setRows(5);
        jScrollPane1.setViewportView(txtSelected);

        lblTotal.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        lblTotal.setText("123,123,123원");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPay))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(175, 175, 175)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(storeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(storeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(storeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(storeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new storeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkCheeseball;
    private javax.swing.JCheckBox ChkCider;
    private javax.swing.JCheckBox ChkCoke;
    private javax.swing.JCheckBox ChkFanta;
    private javax.swing.JCheckBox ChkHotdog;
    private javax.swing.JCheckBox ChkIceAmericano;
    private javax.swing.JCheckBox ChkIceTea;
    private javax.swing.JCheckBox ChkNacho;
    private javax.swing.JCheckBox ChkSquid;
    private javax.swing.JCheckBox ChkSweet;
    private javax.swing.JCheckBox ChkWater;
    private javax.swing.JCheckBox btnNutty;
    private javax.swing.JCheckBox btnOnion;
    private javax.swing.JButton btnPay;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextArea txtSelected;
    // End of variables declaration//GEN-END:variables
}
